shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - 'vite@5.4.21'
  - '@vitejs/plugin-legacy@5.3.2'
  - 'detect-port@1.6.1'
  - 'chokidar@4.0.3'
  - 'semver@6.3.1'
  - 'synckit@0.9.3'
