/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by @uni-ku/bundle-optimizer
declare module '*?async' {
  const component: any
  export = component
}
declare module 'wot-design-uni/components/wd-button/wd-button.vue?async' {
  const component: typeof import('wot-design-uni/components/wd-button/wd-button.vue')
  export = component
}
declare module 'wot-design-uni/components/wd-cell/wd-cell.vue?async' {
  const component: typeof import('wot-design-uni/components/wd-cell/wd-cell.vue')
  export = component
}
declare module 'wot-design-uni/components/wd-picker/wd-picker.vue?async' {
  const component: typeof import('wot-design-uni/components/wd-picker/wd-picker.vue')
  export = component
}
